env:
  - name: DATABASE_CLIENT
  - value: postgres
  - name: DATABASE_HOST
  - value: 172.30.200.90
  - name: DATABASE_PORT
  - value: '5432'
  - name: DATABASE_NAME
  - valueFrom:
  -   secretKeyRef:
  -     name: postgresql
  -     key: database-name
  - name: DATABASE_USERNAME
  - valueFrom:
  -   secretKeyRef:
  -     name: postgresql
  -     key: database-user
  - name: DATABASE_PASSWORD
  - valueFrom:
  -   secretKeyRef:
  -     name: postgresql
  -     key: database-password
  - name: APP_NAME
  - value: bk-strapi
  - name: NODE_ENV
  - value: production
